<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Description>
            Provides integration of RabbitMQ with MassTransit's integration of Elsa.
        </Description>
        <PackageTags>elsa extension module service-bus masstransit rabbitmq</PackageTags>
    </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MassTransit.RabbitMQ" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="D:\repos\elsa-extensions-main\src\modules\servicebus\Elsa.ServiceBus.MassTransit\Elsa.ServiceBus.MassTransit.csproj" />
	</ItemGroup>

</Project>
