<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <!-- Elsa.Studio.Agents -->
    <ItemGroup Condition="'$(UseProjectReferences)' == 'true' and '$(MSBuildProjectName)' == 'Elsa.Studio.Agents'">
        <ProjectReference Include="D:\repos\elsa-studio-main\src\modules\Elsa.Studio.Workflows\Elsa.Studio.Workflows.csproj"/>
    </ItemGroup>

</Project>